### ISSUE TITLE
Resources missing for Concord

### ISSUE THREAD

**Issue by rookboom** [jpaulm/csharpfbp#1]
Hi,

The resource files are missing in the Concord project:

fake_latin.txt etc

Johan

**Comment by jpaulm** [comment]
Sorry about that!  I think it's fixed now!  Except that Resources has somehow been changed to resources - if this is a problem, please let me know!  Thanks.

**Comment by jpaulm** [comment]
Hope everything is OK now!

Season's greetings!

Paul

**Comment by rookboom** [comment]
It works now. Thanks!

**Comment by jpaulm** [comment]
Good news!  Thanks for letting me know!
